spring.config.import=optional:file:.env[.properties]

#Supabase DB connection
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

#DB config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

#Email config
spring.mail.host = smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.protocol=smtp
# Enables SMTP authentication
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false

mapbox.api.token=${MAPBOX_APIKEY}

nominatim.api.geo-url=https://nominatim.openstreetmap.org/search

# JWT configuration
jwt.secret-key=${JWT_SECRETKEY}
# In Milliseconds
jwt.expiration-time=3600000

spring.web.error.include-message=always

# Redis caching
spring.data.redis.url=${REDIS_URL}

# Use port 8080, unless prod gives one
server.port=${PORT:8080}